- name: Install nginx
  hosts: web
  become: true

  vars:
    ansible_ssh_common_args: '-o ForwardAgent=yes'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
